import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import PanelLayout from "./_provider/panel-layout";
import type { Session } from "next-auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Настройка и управление производством",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode;
  session: Session
}) {
  return (
    <html lang="ru">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <PanelLayout session={session}>
            {children}
          </PanelLayout>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
